version: '3.8'  # Docker Compose file version

services:
  # NGINX Web Server
  nginx:  # ✅ Fixed typo: "nignx" → "nginx"
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"  # Maps port 80 on host to port 80 in container
    volumes:
      - ./nginx_data:/usr/share/nginx/html  # Mounts local html files into NGINX
    networks:
      - my_network  # Connects to the shared user-defined network
    environment:
      - NGINX_HOST=localhost  # Environment variable (not used by default NGINX)
      - NGINX_PORT=80         # Optional env variable

  # Alpine Linux (lightweight container)
  alpine:
    image: alpine:latest
    container_name: alpine_container
    networks:
      - my_network
    volumes:
      - ./alpine_data:/data  # Mounts local folder to /data in container
    environment:
      - ALPINE_PORT=8080  # ✅ Fixed missing space after dash

  # Redis (in-memory data store)
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Exposes Redis default port
    networks:
      - my_network
    volumes:
      - redis_data:/data  # Persists Redis data
    environment:
      - REDIS_PORT=6379  # Optional, not used by default Redis image

# Named volumes for persistence
volumes:
  redis_data:
  nginx_data:
  alpine_data:

# User-defined bridge network
networks:
  my_network:
    driver: bridge
